#ifndef GAME_CONFIG_H
#define GAME_CONFIG_H

#define TILE_SIZE 16
#define WORLD_WIDTH 100
#define WORLD_HEIGHT 100

#define CHUNK_WIDTH 16
#define CHUNK_HEIGHT 9

#define SCREEN_TILES_WIDTH 16
#define SCREEN_TILES_HEIGHT 9

#define MAX_ACTIVE_ENTITIES 256

#define MAX_TEXTURES 256

#endif
